"""
scripts/create_prs.py
=====================
Create GitHub pull requests for both branches to merge into main.

Usage:
    $env:GITHUB_TOKEN = "ghp_your_token_here"
    python scripts/create_prs.py
"""

import os
import json
import textwrap
import urllib.request
import urllib.error

GITHUB_REPO = "okayenu/git-tutorial"
BRANCH_MAIN = "main"


def create_pr(branch: str, title: str, body: str) -> dict:
    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        print(f"ERROR: GITHUB_TOKEN not set. Set it with: $env:GITHUB_TOKEN = 'ghp_...'")
        return {}

    payload = json.dumps({
        "title": title,
        "head": branch,
        "base": BRANCH_MAIN,
        "body": body,
    }).encode("utf-8")

    url = f"https://api.github.com/repos/{GITHUB_REPO}/pulls"
    req = urllib.request.Request(
        url,
        data=payload,
        headers={
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read().decode())
            print(f"Created PR: {data.get('html_url')}")
            return data
    except urllib.error.HTTPError as e:
        body_text = e.read().decode()
        if e.code == 422 and "already exists" in body_text:
            print(f"PR for '{branch}' already exists — skipping.")
        else:
            print(f"HTTP {e.code}: {body_text[:300]}")
        return {}


if __name__ == "__main__":
    create_pr(
        branch="features",
        title="Features: Tasks 1–11, 13–16, 21–28, 30–42, 44, 46, 49",
        body=textwrap.dedent("""
            ## Features Branch → main

            This PR merges all **standard feature improvements** from the Fashion-MNIST
            CNN improvement roadmap (Tasks 1–11, 13–16, 21–28, 30–42, 44, 46, 49).

            ### Included Tasks
            - **Data & Preprocessing**: normalization, augmentation, tf.data pipeline,
              standardization, class distribution, hold-out split (Tasks 1–9)
            - **Model Architecture**: BatchNorm, deeper CNN, GAP, VGG-style, L2 reg (Tasks 10–11, 15–16)
            - **Training & Optimization**: early stopping, checkpointing, LR scheduling,
              label smoothing, optimizer comparison, batch size sweep (Tasks 21–28)
            - **Evaluation**: confusion matrix, per-class accuracy, error analysis,
              ROC-AUC, calibration, latency benchmark (Tasks 30–36)
            - **Code Quality**: Python modules refactor, unit tests, docstrings,
              config.py, requirements.txt, random seeds (Tasks 37–42)
            - **MLOps**: SavedModel export, prediction CLI (Tasks 44, 46)
            - **Docs**: Final report, changelog, retrospective, quickstart (Task 49)

            ### Commits
            1,771 backdated commits spanning March 31 – January 1, 2026.

            > Auto-generated by `scripts/create_prs.py`
        """).strip(),
    )

    create_pr(
        branch="risky-features",
        title="Risky Features: Tasks 12, 17–20, 43, 45, 47–48, 50",
        body=textwrap.dedent("""
            ## Risky-Features Branch → main

            This PR merges all **experimental / high-risk improvements** from the
            Fashion-MNIST CNN improvement roadmap.

            ### Included Tasks
            - **Task 12**: ResNet-style skip connections
            - **Task 17**: MobileNetV2 transfer learning (ImageNet pretrained)
            - **Task 18**: EfficientNetB0 transfer learning
            - **Task 19**: Ensemble model (3–5 models, averaged softmax)
            - **Task 20**: Lightweight <100K parameter edge model
            - **Task 43**: MLflow / Weights & Biases experiment tracking
            - **Task 45**: TFLite conversion and latency benchmark
            - **Task 47**: Grad-CAM visualization
            - **Task 48**: t-SNE / UMAP feature embedding plot
            - **Task 50**: Gradio interactive demo

            ### Commits
            525 backdated commits spanning risky-task windows through January 3, 2026.

            > Auto-generated by `scripts/create_prs.py`
        """).strip(),
    )
